### ISSUE TITLE
Kolorowanie

### ISSUE THREAD

**Issue by TheMolkaPL** [Kamilkime/Pisanie-pluginow#1]
Obecnie wykorzystujesz znak paragrafu `§`, aby kolorować [String](http://docs.oracle.com/javase/6/docs/api/java/lang/String.html). Jest to błąd, ponieważ powinieneś wykorzystywać [enum ChatColor](http://jd.bukkit.org/rb/apidocs/org/bukkit/ChatColor.html).

Argumenty wyższości ChatColor.
* Jeżeli Mojang zmieni kodowanie, nie będzie to niszczyło pluginów.
* Plik musi zostać zapisany w formacie UTF-8, aby paragraf został zapisany - Eclipse domyślnie nie zapisuje plików w UTF-8.
* ChatColor jest dużo bardziej przejrzysty w czytaniu.
* ChatColor wspiera tłumaczenie jakiegokolwiek znaku kolorowania na obiekt ChatColor (przykładowo w [Essentials](https://github.com/essentials/Essentials) jest to `&`).

**Comment by Kamilkime** [comment]
Ciekawe, bo to są 2 szkoły - ja wiele razy słyszałem, że lepszy jest `§`, więc go używam

**Comment by TheMolkaPL** [comment]
A co z konsolą? Jeżeli wyślemy paragraf do konsoli, to ona go nie rozczyta.
Jeżeli użyjemy ChatColor, wszelkie kolory zostaną zignorowane.

**Comment by Kamilkime** [comment]
Mi wyświetla konsola jak używam `§`, jak używam ChatColor - nie
